#!/usr/bin/env node

/**
 * Environment Setup Script
 * 
 * This script helps set up environment files for different environments.
 * Usage: node scripts/setup-env.js [dev|uat|prod]
 */

const fs = require('fs');
const path = require('path');

const environments = {
  dev: {
    file: '.env.development',
    env: 'development',
    apiBaseUrl: 'http://localhost:3000/api',
    backendUrl: 'http://localhost:8000',
  },
  uat: {
    file: '.env.uat',
    env: 'uat',
    apiBaseUrl: 'https://api-uat.yourdomain.com/api',
    backendUrl: 'https://backend-uat.yourdomain.com',
  },
  prod: {
    file: '.env.production',
    env: 'production',
    apiBaseUrl: 'https://api.yourdomain.com/api',
    backendUrl: 'https://backend.yourdomain.com',
  },
};

function createEnvFile(envConfig) {
  const content = `# ${envConfig.env.toUpperCase()} Environment Configuration
# Generated by setup-env.js

NEXT_PUBLIC_ENV=${envConfig.env}
NEXT_PUBLIC_API_BASE_URL=${envConfig.apiBaseUrl}
NEXT_PUBLIC_BACKEND_URL=${envConfig.backendUrl}

# Add other ${envConfig.env}-specific variables here
# NEXT_PUBLIC_ANALYTICS_ID=
# NEXT_PUBLIC_SENTRY_DSN=
`;

  const filePath = path.join(process.cwd(), envConfig.file);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`✅ Created ${envConfig.file}`);
}

function setupAllEnvironments() {
  console.log('Setting up all environment files...\n');
  Object.values(environments).forEach(createEnvFile);
  console.log('\n✨ All environment files created successfully!');
  console.log('\nNext steps:');
  console.log('1. Update the API and backend URLs in each .env file');
  console.log('2. Add any additional environment-specific variables');
  console.log('3. Use npm run dev:dev, npm run dev:uat, or npm run build:prod');
}

function setupSpecificEnvironment(envName) {
  const env = environments[envName];
  if (!env) {
    console.error(`❌ Unknown environment: ${envName}`);
    console.log('Available environments: dev, uat, prod');
    process.exit(1);
  }
  createEnvFile(env);
  console.log(`\n✨ ${env.file} created successfully!`);
  console.log('Please update the URLs with your actual backend endpoints.');
}

// Main execution
const args = process.argv.slice(2);
const envArg = args[0];

if (!envArg) {
  setupAllEnvironments();
} else {
  setupSpecificEnvironment(envArg.toLowerCase());
}

